[package]
name = "time_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
dbus = "0.9.7"

[dependencies.rusqlite]
version = "0.29.0"
features = ["bundled"]
